### ISSUE TITLE
Budget version?

### ISSUE THREAD

**Issue by gadgetmies** [Architeuthis-Flux/Jumperless#14]
Would it be possible to create a cheaper option by dropping the RGB leds from the design? Those are really cool, but the $299 price is IMHO a bit steep. I think it would be enough to have one led per row / column to visualise the connections. AFAICT one could then use a cheap protoboard soldered to the PCB and thus not need the custom connectors and protoboard print.

Any thoughts?

**Comment by Architeuthis-Flux** [comment]
You'd be surprised at how little removing the LEDs would affect the overall cost. 90% of the BOM cost is the crosspoint switching matrix and the power supplies to drive them. So a super stripped-down version would end up being like $250.

The breadboard footprint on the PCB does have a fallback to solder an off the shelf breadboard to it (if you don't populate the LEDs or cut a channel through the clips), but the amount of heat required to melt solder on the other side of the board causes some serious warping issues. I've done it before, but there's no way I could convince a factory to do that for me.

The only workable way to get the cost down is having fewer points to switch, so an even smaller breadboard. 

Or just wait a while for the inevitable impossibly cheap Chinese clones to come out. I'll do my best to have my firmware and stuff support them when they do, because that would take a lot of pressure off me to get these into the hands of everyone who wants them.
