### ISSUE TITLE
Recommending CH446Q for smaller package 

### ISSUE THREAD

**Issue by DeqingSun** [Architeuthis-Flux/Jumperless#2]
I just came across this project and I remember datasheet of CH446Q mentioned it was functionally compatible to MT8816AP, although not pin compatible. Hope this is useful information if you want a newer or thinner chip.

**Comment by Architeuthis-Flux** [comment]
I've been aware of this chip for a while and was skeptical to try it out. But your comment finally convinced me to give it another look. 

I switched microcontrollers to the RP2040 and it doesn't quite have enough IO to do the parallel addressing, but as it turns out, the CH446Q can accept commands over serial too.

And LCSC had them in stock so I can just order them assembled now.

So the new revision uses them, just wanted to say thanks for the suggestion.
