### ISSUE TITLE
Alternative ways to configure the board without Wokwi?

### ISSUE THREAD

**Issue by rdragonrydr** [Architeuthis-Flux/Jumperless#25]
So I've got absolutely no right to ask, but I'm a little uncomfortable using a web application as part of my development chain, let alone one that I can't seem to find full source code for (I was able to find some for their ancillary systems but not wokwi core. Maybe I'm wrong though).

Is there currently any way to use Jumperless direct from the bridge/desktop app, or plans to add that? I'm alright doing something like telling it to connect these two rows on the breadboard and repeat for N, I don't really need a full GUI or a Fritzing/KiCad clone or interface (though that would be nice).

I would try to do it myself but I've been suffering from burnout and was ironically looking into this in hopes it would get me back into designing circuits and programming stuff.

**Comment by Architeuthis-Flux** [comment]
You totally have a right to ask, and you're in luck. 

There are a few ways you could do this. Listed from simple to powerful.
## Just a straight up text file pasted in
The most stupidly basic way would just keep a text document with a list of connections preceded by 'f ' and just paste it into the window. You'll still need to give it a random Wokwi link to get the app started, but each time you paste a netlist it will clear any previous netlist.

For example, 
`f 1-2,GND-5,DAC0-35, A0-50, d1-56, D0-55, 15-20, +5V-25,`
Will give you
<img width="686" alt="Screenshot 2024-01-11 at 6 08 09 PM" src="https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/30232231-77f4-40d5-a7d9-d29610616789">
It's pretty loose with what it accepts, just make sure the last bridge ends with a comma. Here's a list that shows what it will accept for the special functions
![Screenshot 2024-01-11 at 6 02 44 PM](https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/8e311c6e-b46f-4d9f-8229-7e68eb09150b)



## jlctl

@nilclass has been working on [jlctl](https://github.com/nilclass/jlctl/tree/develop), which is an open source text based UI written in Rust. Which is super helpful for keeping track of your netlist and sending it to the Jumperless among other things. 

![Screenshot 2024-01-11 at 6 14 55 PM](https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/a75e635b-66a4-4fd5-8610-dee8e9e15ff0)
![Screenshot 2024-01-11 at 6 16 38 PM](https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/7cf97667-f371-488b-83fb-fc45ab1e892e)
This is can also start a local server to be used with...

## Jumperlab

Another awesome bit of software from @nilclass, Jumperlab is a GUI for the Jumperless written in Node.js and stuff. Yeah it runs in a browser because we're in the future and everything does but it's still running completely locally on your machine. It's a work-in-progress but it's coming along super quickly. And it's pretty damn close to being useable as of today. 
<img width="1727" alt="Screenshot 2024-01-11 at 6 31 45 PM" src="https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/7cf111f3-3851-4266-a2f9-2843ae2c5ffc">


I hope this can get some anti-burnout juices flowing in you!
