### ISSUE TITLE
Jumperless Gets Hot

### ISSUE THREAD

**Issue by burnt-past** [Architeuthis-Flux/Jumperless#34]
During operation, the CH446Q chips located on the rear side of the PCB become heated to temperatures exceeding 200°F. As they reach this temperature, the outputs appear to cease functioning correctly. Initially, the grounding (GND) and power (VCC) connections are affected, followed by interruptions in pin-to-pin connectivity.

**Comment by Architeuthis-Flux** [comment]
Yeah that shouldn't be happening. First, let me know your name so I can ship you out a fresh one and parts to fix the old one. 

It might not be permanently damaged so let's do some troubleshooting.

- Was there external power applied somewhere on the breadboard before you plugged it in? Or just send a pic of your setup.

- Is one particular chip much hotter than the others?

- Roughly when was the firmware last updated?

- With the Rail Selection Switch at the top (+-8V) what voltage do the rails read when it's first plugged in? If it's connected through a USB hub, does that change when you use something else to power it (like USB charger plugged into the wall)?

I'll try to think of more possible causes. But these should get us started in the right direction.

**Comment by burnt-past** [comment]
Hey!

My name is Alex Woolum. But I ordered the jumperless through JLC at the time since you didn't have stock in your shop a awhile ago. I've always noticed it getting hot since I've had it though.

There was an external power supply attached to the jumperless in this instance. But I turned it off during power cycles of the jumperless. I was using optocouplers with an isolated power supply.

At Boot the rails are defaulting to 3.3 volts even with the switch in the 5 volt position. 

I'm on the most current firmware.

Thanks for being so prompt on your response!

**Comment by Architeuthis-Flux** [comment]
Oh hey Alex,

That almost sounds like some part on the order was flipped, maybe even the Rail Supply Switch. JLCPCB has a tendency to just randomly rotate components. Someone in the Discord ordered 10 and even after rotating the parts correctly in the order, JLC flipped all the LEDs. So brutal.

From the time you ordered the clips, you have a Rev 2 with the old style clips, so it's possible something in the firmware is messing with it. My first thought is that I might have broke the code that sets the DACs to 0V at startup, and that's drawing too much current from the +-9V supply so it's sagging to a lower voltage and possibly causing this.

Anyway, have you moved since October? It's killing me to have people using my less-polished work, so I'm going to send you a fresh Rev 3 and then you can compare the orientations of the parts and make sure they're the same (or just use that and put the Rev 2 in a drawer, ha.)

If you want, send me close up photos of the front and back of the board and I might be able to spot the issue.

**Comment by Architeuthis-Flux** [comment]
![x-16](https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/ea01d955-fc70-47c5-901d-a5a380181dd8)
![x-17](https://github.com/Architeuthis-Flux/Jumperless/assets/20519442/4568729b-0bb8-425c-b647-0e1e45b1fb4b)

btw here's the correct orientation of the switch (note the little detent thing on one side), even though it seems weird it would work at all with it was upside down.

**Comment by burnt-past** [comment]
Hey, Still I'm still at the same address!

Here is the thermal on the board. I swapped those out, and they ended up frying again.

![20240710120010](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/1ad6be1a-9d90-4311-8623-719c7255b4c3)

Sorry for the potato photos. I need to figure out what's going on with my phone camera.  As far as I can tell, the components are all in the correct orientation.

![20240711_083404](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/c4810a1f-c6c9-4695-8e2f-cba0a7204e2c)
![20240711_083417](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/263e9fb2-e72c-40c5-a2fc-73868e1fd3ba)

![20240711_083413](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/f0369f1a-bf53-49c3-8671-2e51a81188d1)
![20240711_083409](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/4d596da6-514a-49a6-963b-b325ae6e75e7)
![20240711_083420](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/bf6e44d0-4fb3-408e-9aeb-e7ed90bd9d02)

**Comment by burnt-past** [comment]
I assume it relates to the reset lines since the outputs get locked at 2V. But I'm not 100% sure; I don't have any experience with these ICs.

I'll have to depopulate those ICs next week, as I don't have time today. I'll let you know what the outcome is.

Thanks for sending out that replacement btw!

Here's the top view:

![20240711_123411](https://github.com/Architeuthis-Flux/Jumperless/assets/5716441/2b23c0ec-a418-42a9-9833-26133cd58da0)
